refined!

diff --git a/backup2device b/backup2device
--- a/backup2device
+++ b/backup2device
@@ -2,23 +2,19 @@
 
 # Script: backup2device.sh
 # Author: Ajay G
-# Description: Script for backing-up $HOME or specified dirs to external devices/drives or to local dirs.
+# Description: A flexible script to back up the $HOME directory or user-specified directories to an external drive/mtp-device or a local backup directory.
 
 # ERROR HANDLING
-# -e : (errexit) Exit immediately if any command returns a non-zero status
-# -u : (nounset) Treat unset variables as errors and exit immediately
-# -x : (xtrace) Print commands and their arguments as they are executed
-# -o pipefail : Pipeline returns the exit status of the last command to fail, or zero if all succeed
 set -euo pipefail
 
-# VARIABLES
+# IMPORTANT VARIABLES
 # File name of the 'backed-up' archive file
-BACKUP_FILE_NAME="$(date +%Y%m%dT%H%M%S)--$(hostname)__$(cat /etc/*-release | grep PRETTY_NAME | cut -d'=' -f2 | tr -d '" ()').tar"
+BACKUP_FILE_NAME="$(date +%Y%m%dT%H%M%S)--$(hostname)__$(cat /etc/*-release | grep PRETTY_NAME | cut -d'=' -f2 | tr -d '" ()').tar.gz"
 
 # Directories or files to 'exclude' from $HOME
 # Specify only the filename
 # eg; (".cache" "Desktop" "Downloads" "Music" "Videos")
-EXCLUDE_DIRS=("*")
+EXCLUDE_DIRS=(".cache")
 
 # Directories or files to 'include' other than from $HOME
 # Specify the full filename i.e., including the path
@@ -26,53 +22,63 @@ EXCLUDE_DIRS=("*")
 INCLUDE_DIRS=()
 
 # Options for tar
-# -c - create archive
-# -z - use gzip / -J - use xz
-# -p - preserve permissions
-# -f - output file
-TAR_OPTIONS="-czpf"
+# -z : use gzip / -J : use xz (Remember to add .gz or .xz to BACKUP_FILE_NAME)
+# -p : preserve permissions
+# keep -c at the beginning and -f at the end
+TAR_OPTIONS="-czf"
 
+# DEFINE COLORS
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+BLUE='\033[0;34m'
+RESET='\033[0m' # No Color
 # WARN
-[ -z "$TAR_OPTIONS" ] && echo "ERROR: TAR_OPTIONS is empty in the script; fatal!"
-[ ${#EXCLUDE_DIRS[@]} -eq 0 ] && echo "Warning: EXCLUDE_DIRS is empty in the script; not fatal!"
+[ -z "$TAR_OPTIONS" ] && echo -e "${RED}ERROR: TAR_OPTIONS is empty in the script; fatal!${RESET}"
+[ ${#EXCLUDE_DIRS[@]} -eq 0 ] && echo "${YELLOW}Warning: EXCLUDE_DIRS is empty in the script; not fatal!${RESET}"
 DEPENDENCIES=(tar gpg ls lsblk nl read echo mkdir)
 for dep in "${DEPENDENCIES[@]}"; do
-    command -v "$dep" &> /dev/null || { echo "Error: $dep is not installed. Please install it to continue."; exit 1; }
+    command -v "$dep" &> /dev/null || { echo "${RED}Error: $dep is not installed. Please install it to continue.${RESET}"; exit 1; }
 done
 
-# FUNCTIONS
+# Get a list of external drives (excluding internal drives and loop devices)
+DRIVES=$(lsblk -d -o NAME,FSTYPE,SIZE,MOUNTPOINT -e 7,1 | awk '$1 ~ /^sd/ && $4 != "/" {print $0}')
+# Get a list of gvfs-mtp mounted devices
+# TODO; support for other mtp mountpoints;
+MTP_DEVICES=$(ls -1t /run/user/$UID/gvfs/)
+# Local format
+LOCAL="Local $(df -h --output=avail $HOME | sed -n '2p') $HOME"
+# Check if any drives or mtp-devices are found
+if [ -z "$DRIVES" ]; then
+    DRIVES="No External Drives found!"
+fi
+if [ -z "$MTP_DEVICES" ]; then
+    MTP_DEVICES="No MTP-Devices/Phones found!"
+fi
 # First prompt
-echo "Backup to:"
-echo -e "External drive\nMTP Phone/Device\nLocal" | nl -s ') '
-read -p "Choose a Number and Enter:" choice_num
-# 1. External drive
-if [ "$choice_num" = "1" ]; then
-    # Get a list of external drives (excluding internal drives and loop devices)
-    DRIVES=$(lsblk -d -o NAME,FSTYPE,SIZE,MOUNTPOINT -e 7,1 | awk '$1 ~ /^sd/ && $4 != "/" {print $0}')
-    # Check if any drives are found
-    if [ -z "$DRIVES" ]; then
-	echo "No external drives found."
-	exit 1
-    fi
-    # Display drives in a numbered menu
-    echo "Select an external drive:"
-    echo "$DRIVES" | nl -s ') '
-    read -p "Choose a Number and Enter:" drive_num
+# Display drives or mtp-devices in a numbered menu
+echo "Where to backup:"
+echo -e "$DRIVES\n$MTP_DEVICES\n$LOCAL" | nl -s ') '
+read -p "$(echo -e "${BLUE}Choose a Number and Enter: ${RESET}")" choice_num
+CHOICE=$(echo -e "$DRIVES\n$MTP_DEVICES\n$LOCAL" | sed -n "${choice_num}p")
+# Process the choice
+if [ "$DRIVES" != "No External Drives found!" ] && echo "$DRIVES" | grep -q "^$CHOICE$"; then
+    echo "Selected: $CHOICE"
     # Get the selected drive's mountpoint
-    DRIVE_SEL=$(echo "$DRIVES" | sed -n "${drive_num}p" | awk '{print $4}')
+    DRIVE_SEL=$(echo "$CHOICE" | awk '{print $4}')
     # Check if the drive is mounted
     if [ -z "$DRIVE_SEL" ]; then
-	echo "Please mount the Drive and try again!"
+	echo -e "${RED}Please mount the Drive and try again!${RESET}"
 	exit 1
     fi
     # Prompt for confirmation
-    read -p "Proceed with backup on $DRIVE_SEL/Backups ? (y/n): " confirm
+    read -p "$(echo -e "${BLUE}Proceed with backup on $DRIVE_SEL/Backups ? (y/n): ${RESET}")" confirm
     if [ "$confirm" != "y" ]; then
-	read -e -p "Enter location (start from $DRIVE_SEL): " confirm_loc
+	read -e -p "$(echo -e "${BLUE}Enter location (start from $DRIVE_SEL): ${RESET}")" confirm_loc
 	EXTERNAL_DIR="$confirm_loc"
-	read -e -p "Proceed with backup to $EXTERNAL_DIR (y/n): " confirmy
+	read -p "$(echo -e "${BLUE}Proceed with backup to $EXTERNAL_DIR (y/n): ${RESET}")" confirmy
 	if [ "$confirmy" != "y" ]; then
-	    echo "Backup cancelled."
+	    echo -e "${RED}Backup cancelled.${RESET}"
 	    exit 0
 	fi
     else
@@ -80,46 +86,47 @@ if [ "$choice_num" = "1" ]; then
     fi
     mkdir -p "$EXTERNAL_DIR"
     DEST="$EXTERNAL_DIR/$BACKUP_FILE_NAME"
-    # 2. MTP Phone/Device
-elif [ "$choice_num" = "2" ]; then
-    # Check for gvfs-mtp mountpoint
-    DEVICE_MOUNT="/run/user/$UID/gvfs/mtp*"
-    if ! ls $DEVICE_MOUNT >/dev/null 2>&1; then
-	echo "No device mounted. Connect your device via USB."
-	exit 1
-    fi
-    # Prompt for confirmation
-    read -p "$(ls -1t /run/user/$UID/gvfs/) detected. Proceed with backup? (y/n): " confirm
+elif [ "$MTP_DEVICES" != "No MTP-Devices/Phones found!" ] && echo "$MTP_DEVICES" | grep -q "^$CHOICE$"; then
+    echo "Selected: $CHOICE"
+    # Get the selected mtp-device's mountpoint
+    DEVICE_SEL="/run/user/$UID/gvfs/$(ls -1tb /run/user/$UID/gvfs/)/Internal shared storage"
+    read -p "$(echo -e "${BLUE}Proceed with backup on $DEVICE_SEL/Backups ? (y/n): ${RESET}")" confirm
     if [ "$confirm" != "y" ]; then
-	echo "Backup cancelled."
-	exit 0
+	read -e -p "$(echo -e "${BLUE}Enter location (start from $DEVICE_SEL): ${RESET}")" confirm_loc
+	DEVICE_DIR="$confirm_loc"
+	read -p "$(echo -e "${BLUE}Proceed with backup to $DEVICE_DIR (y/n): ${RESET}")" confirmy
+	if [ "$confirmy" != "y" ]; then
+	    echo -e "${RED}Backup cancelled.${RESET}"
+	    exit 0
+	fi
+    else
+	DEVICE_DIR="/run/user/$UID/gvfs/$(ls -1tb /run/user/$UID/gvfs/)/Internal shared storage/Backups"
     fi
-    DEVICE_DIR="/run/user/$UID/gvfs/$(ls -1tb /run/user/$UID/gvfs/)/Internal shared storage/Backups"
     mkdir -p "$DEVICE_DIR"
     DEST="$DEVICE_DIR/$BACKUP_FILE_NAME"
-    # TODO; support for other mtp mountpoints;
-    # 3. Local
-elif [ "$choice_num" = "3" ]; then
-    read -p "Proceed with backup to ~/Downloads/Backups (y/n): " confirm
+elif [ "$CHOICE" = "$LOCAL" ]; then
+    echo "Selected: $CHOICE"
+    read -p "$(echo -e "${BLUE}Proceed with backup to ~/Downloads/Backups (y/n): ${RESET}")" confirm
     if [ "$confirm" != "y" ]; then
-	read -e -p "Enter location: " confirm_loc
+	read -e -p "$(echo -e "${BLUE}Enter location: ${RESET}")" confirm_loc
 	LOCAL_DIR="$confirm_loc"
 	read -p "Proceed with backup to $LOCAL_DIR (y/n): " confirmy
 	if [ "$confirmy" != "y" ]; then
-	    echo "Backup cancelled."
+	    echo -e "${RED}Backup cancelled.${RESET}"
 	    exit 0
 	fi
     else
 	LOCAL_DIR="$HOME/Downloads/Backups"
     fi
     mkdir -p "$LOCAL_DIR"
-    DEST="$LOCAL_DIR/$BACKUP_FILE_NAME"
+    EXCLUDE_DIRS+=("$LOCAL_DIR")
+    DEST="$LOCAL_DIR/$BACKUP_FILE_NAME"    
 else
-    echo "Invalid choice"
+    echo -e "${RED}Invalid response: ${RESET}$CHOICE"
     exit 1
 fi
 
-# Functions for appending dirs mentioned in EXCLUDE_FLAGS and INCLUDE_FLAGS to tar cmd
+# Functions for appending dirs mentioned in EXCLUDE_FLAGS and INCLUDE_FLAGS into tar cmd
 EXCLUDE_FLAGS=()
 for dir in "${EXCLUDE_DIRS[@]}"; do
     EXCLUDE_FLAGS+=("--exclude=$dir")
@@ -129,16 +136,35 @@ for dir in "${INCLUDE_DIRS[@]}"; do
     INCLUDE_FLAGS+=("$dir")
 done
 # To write tar archive directly to destination
-read -p "Proceed with backup Encryption (y/n): " confirm
-if [ $confirm != "y" ]; then
-    tar $TAR_OPTIONS "$DEST" "${INCLUDE_FLAGS[@]}" -C "$HOME" "${EXCLUDE_FLAGS[@]}" .
+read -p "$(echo -e "${BLUE}Proceed with backup Encryption (y/n): ${RESET}")" confirm
+if [ "$confirm" != "y" ]; then
+    tar $TAR_OPTIONS "$DEST" "${INCLUDE_FLAGS[@]}" -C "$HOME" "${EXCLUDE_FLAGS[@]}" . &
+    MESSAGE="Run '$ tar "${TAR_OPTIONS/c/x}" <backup>.tar.gz' to extract!"
 else
-    tar $TAR_OPTIONS - "${INCLUDE_FLAGS[@]}" -C "$HOME" "${EXCLUDE_FLAGS[@]}" . | gpg --symmetric -o "$DEST".gpg
+    tar $TAR_OPTIONS - "${INCLUDE_FLAGS[@]}" -C "$HOME" "${EXCLUDE_FLAGS[@]}" . | gpg --symmetric -o "$DEST".gpg &
+    MESSAGE="Run '$ gpg -d <backup>.tar.gz | tar "${TAR_OPTIONS/c/x}" -' to extract!"
 fi
+pid=$!
+echo "Press 'C-c' to cancel"
+cancel_fun() {
+    kill $pid 2>/dev/null
+    echo -e "${RED}Backup cancelled.${RESET}"
+    exit 0
+}
+trap cancel_fun SIGINT SIGTERM EXIT
+# Display size metrics while process is running
+TOTALSIZE="$(du -sh "${EXCLUDE_FLAGS[@]}" "$HOME")"
+while kill -0 "$pid" 2>/dev/null; do
+    printf '\rBacking up %s - Current archive size %s' "$TOTALSIZE" "$(du -sh $DEST | awk '{print$1}')"
+    sleep 1
+done
 # VERIFY
+wait $pid
 if [ $? -eq 0 ]; then
-    echo "Backup successfully created at $DEST"
+    echo -e "${GREEN}Backup successfully created at $DEST${RESET}"
+    echo -e "${YELLOW}$MESSAGE${RESET}"
+    exit 0
 else
-    echo "Failed to create backup at $DEST"
+    echo -e "${RED}Failed to create backup at $DEST${RESET}"
     exit 1
 fi
